disabled_rules:
  - trailing_whitespace
  - todo

opt_in_rules:
  - empty_count
  - closure_spacing
  - explicit_init
  - force_unwrapping

analyzer_rules:
  - unused_import

line_length:
  warning: 120
  error: 200

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 400
  error: 500

function_body_length:
  warning: 50
  error: 100

type_name:
  min_length: 3
  max_length: 50

identifier_name:
  min_length: 2
  max_length: 50

excluded:
  - .build
  - Pods
  - DerivedData
